### ISSUE TITLE
read srt in zip

### ISSUE THREAD

**Issue by URBigFan** [peno64/service.subtitles.localsubtitle#10]
only 1 thing missing is addon can't find & read zip subtitles from subscene downloaded. i know it's simple to extract zip before use addon. but if it's possible like subscene addon. should it better & perfect.

**Comment by peno64** [comment]
@URBigFan 
Thanks for the suggestion. Your request has been implemented.
The addon is now in repository https://peno64.github.io/repository.peno64/
Another addition to the addon is that it now also supports 2 subtitle files. One at the bottom and one at the top.
