### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by vetiver23** [peno64/service.subtitles.localsubtitle#13]
From today update pysubs 2 module not working...please repair

**Comment by peno64** [comment]
If I am not mistaken, I saw an update of pysubs2 today. Probably they broke something...

**Comment by peno64** [comment]
From what I can see the error is in the update of pysubs2 itself.

This new version uses an import of a python module called whisper which is not there
see https://github.com/bkiziuk/script.module.pysubs2/issues/1
where I report the problem to the developer

**Comment by peno64** [comment]
@vetiver23 
The problem is a missing python file in the update of pysubs2. I asked  the developer to make an update of  his addon asap.

**Comment by vetiver23** [comment]
Thanks Dňa ne 4. 12. 2022 o 10:36 peno64 ***@***.***> napísala(a):
@vetiver23
The problem is a missing python file in the update of pysubs2. I asked  the developer to make an update of  his addon asap.

**Comment by peno64** [comment]
An update of pysubs2 solves the problem

**Comment by vetiver23** [comment]
I've done it thanks so muchDňa st 7. 12. 2022 o 21:11 peno64 ***@***.***> napísala(a):
An update of pysubs2 solves the problem
