### ISSUE TITLE
Place both language subtitles in the bottom

### ISSUE THREAD

**Issue by carlosvsilva** [peno64/service.subtitles.localsubtitle#14]
Hi, is there any chance to be able to place the secondary language subtitle **NOT** on the top of the screen, but on the bottom near the main language subtitle? For language learning this would be important.

Maybe main sub in the bottom left, and secondary sub in the bottom right.
If longer subtitles overflow, then just place them together in the bottom, main lang above, and second lang under.

Is this possible to implement? Thanks

**Comment by peno64** [comment]
In fact yes, this is possible.
I did some tests and both next to each other and below each other is possible at the bottom.

![image](https://github.com/peno64/service.subtitles.localsubtitle/assets/32430988/21735ac5-2ae2-4ecf-a2c3-9298fc5d83f0)

**Comment by carlosvsilva** [comment]
Amazing! Can you release this update? Im running Kodi 20.1 nexus :) 

The ideal situation would be to place the subtitles as low as possible on the screen, on the black bars under the movie to cover the picture the least area possible :)

Outside of this needed functionality: any way to make Kodi auto load subtitles or is always a manual process to ask for an online list from your opensubtitles dual sub provider?
If it's a quick thing, adding the standard DejaVu Sans to the font list that seems native to Kodi would be nice too.
Cheers!

**Comment by peno64** [comment]
I am working on the changes right now. Looking good.

"The ideal situation would be to place the subtitles as low as possible on the screen, on the black bars under the movie to cover the picture the least area possible :)"
I am adding a setting to define the spacing.

"If it's a quick thing, adding the standard DejaVu Sans to the font list that seems native to Kodi would be nice too."
I added this font too.

"Outside of this needed functionality: any way to make Kodi auto load subtitles or is always a manual process to ask for an online list from your opensubtitles dual sub provider?"
That is more difficult. Autoloading is possible. The problem is how should the addon know where it can find the subtitle files (next to the video ?) and especially how it can know the names of the two subtitle files.
This will for sure not something for this release.

**Comment by peno64** [comment]
@carlosvsilva 

A new version of the localsubtitle addon is released via my repo.

Via the settings you can now specify where the two subtitles will be shown. Also the new font and the shift of the subtitles can be chosen there.

Looking forerward to your tests

**Comment by peno64** [comment]
@carlosvsilva 

Did you already try this new version? Does it work for you? Any comments?

**Comment by carlosvsilva** [comment]
Sorry but your repo only displays version 5.4.0 to me, i have all automatic updates on, i tried switching them on and off and still when I browse the repo via Kodi only version 5.4.0 shows up.

While writing this reply I noticed this is a different addon from OpenSubtitles addon. I'm using your OpenSubtitles fork addon for the dual subs, in AndroidTv the only way Im able to watch movies is to get them online, and use your OpenSubtitles addon for the matching subs (in french and portuguese) as configured in Kodi's languages.

My initial goal was for OpenSubtitles, I posted the issue in this repo following your direction. Would you be so kind to implement this in the other add-on for OpenSubtitles? I haven't messed with local subtitles for many years now :) Cheers

**Comment by peno64** [comment]
@carlosvsilva 

Also the opensubtitles in my repo is now adapted.

Looking foreward to your tests.

**Comment by carlosvsilva** [comment]
Hi! Amazing results, thanks a ton.

**Notes**:
I've increased the font size to 22 (55" 4K TV)
I've settled on bottom/bottom for optimal language learning. People in households watching the same movie but reading from 2 different language subtitles benefit best from left/right I think.
With vertical margin 0 the subtitle still starts overlaying the movie picture frame itself. Maybe it requires negative vertical margin (gui doesnt allow now) to put the subtitle under the movie picture, overlaying on the black bars.

**Problems**:
Auto-charset_normalizer fails and corrupts the local characters different from regular english language (ç). I've defaulted to Auto-charset and seems to work fine.
Sometimes in bottom/bottom subtitles, if the language above has the full sentence of the dialogue on display for like 4 seconds, and the other language below, splits the same sentence of dialogue in 2 parts, for 2 seconds each:
 I noticed that while the 1st part displays correctly, the 2nd part of the sentence below will show up **above** the first language that was always above, 1st in reading order, temporarily inverting the order of both languages which is confusing.
But it might be a different "trigger" for this to happen

**Comment by peno64** [comment]
I am affraid that I can't do much about the problems.
It's the ssa format and kodi who descide where to put the subtitles on screen. For the top language I have to provide an extra vertical margin and the result is that if is put over the movie. To make sure that the two subs would not be swapped I even would have to increase that value. I think it has also to do with your font size. The larger you make that, the bigger the change that they can swap. For not to swap I probably would have to increase the vertical margin of the upper subtitle depending on the font size which will mean that it will overlap the video even more.

**Comment by peno64** [comment]
@carlosvsilva 

I made a couple of changes which could fix your problems however no guarantees. The switch of the two subtitles can also be solved by setting a larger vertical margin for the top subtitle than the vertical margin of the bottom subtitle. You may need to experiment with it. It depends of the font chosen, if you display it old or not, ...  The vertical margin can now also be negative. Auto Chardet is now again the default.
