### ISSUE TITLE
Failed to download subtitle https%3A%2F%2Fs3-dub-2.cf.dash.row

### ISSUE THREAD

**Issue by pstkypstky** [peno64/service.subtitles.localsubtitle#15]
Hi,

(Kodi 20.1 + peno1.12.1)

My main purpose is to load dual subs.

When  I try to choose a local sub, in addon "Amazon VOD", I get the error message "https%3A%2F%2Fs3-dub-2.cf.dash.row Failed to download subtitle"

If I use the standard "Browse for subtitle", and load the same sub, it is working.

Can you solve it please? 

Thank you in advance

Regards.

Patrick

**Comment by peno64** [comment]
Can you be more specific.
First of all, the addon. Where can I find it and how and which video are you playing? And please also provide the subtitles you try to play.

**Comment by peno64** [comment]
Is it the prime video amazon vod addon from Sandmann79’s Repository?
I searched https%3A%2F%2Fs3-dub-2.cf.dash.row in google and found that addon. I see for example https://github.com/Sandmann79/xbmc/issues/309 where that text is shown there. It looks that this error is coming from the amazon addon and not from mine.

I tried this addon but it looks like you have to have an account.
I can't do much if I can't simulate your issue...

**Comment by pstkypstky** [comment]
> 
Yes, it is the addon Sandmann79. What is strange is that the standard functionality "Browse for subtitle" does not give that error but unfortunatelly, it does not allow to load dual subtitles...Thanks anyway
