### ISSUE TITLE
It seem that the add-on doesn't fully support ass? 

### ISSUE THREAD

**Issue by asinitial** [peno64/service.subtitles.localsubtitle#3]
The dialog show nothing when browse the folder where the ass file located, and can load normally after changing extension name to srt manually.

**Comment by peno64** [comment]
It was not easy to find out which subtitle extensions kodi supports.
From what I could find, I added following extensions:
.srt, .sub, .ssa, .ass, .idx, .smi, .aqt, .scc, .jss, .ogm, .pjs, .rt, .smi

new version service.subtitles.localsubtitle_1_2_0
