### ISSUE TITLE
Feature Request Select local subtitle when playing strm files

### ISSUE THREAD

**Issue by Dnkhatri** [peno64/service.subtitles.localsubtitle#6]
I am using strm files for the youtube addon. The files are named S01E02.strm S01E02.srt kodi does not detect the file I can manually browse and select the subtitle but if the show has more than a few episodes selecting the correct subtitle takes time and to many clicks. Currently the addon seem to find the file but errors out.

**Comment by peno64** [comment]
You will have to give more information.
A step by step guide line what you do to simulate your issue would be helpfull.
And especially what you exactly expect from the LocalSubtile addon

**Comment by Dnkhatri** [comment]
I use strm files for the youtube addon. Kodi scans them into the database as normal video files but when playing strm files kodi does not detect and select the subtitle files named same as the strm files in the folder. When I use your addon it seems to find the subtitle but gives an error. I would like the addon to select the correct subtitle file so I dont need to manually browse and select the subtitle

**Comment by peno64** [comment]
Auto-find subtitles is not  the purpose of this addon. You always have to go into the LocalSubtitle addon  yourself and you have to select the correct subtitle.
What you ask is out of the scope of this addon and won't be implemented
